pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
    stage('Create EC2 Instance') {
      steps {
        script {
          // Use AWS CLI to create an EC2 instance
          sh 'aws ec2 run-instances --image-id ami-07413789aae50b0e0 --instance-type t2.micro --key-name devopsmachinev1 --security-group-ids sg-03cef694bd8017e60 --subnet-id subnet-07c29685c0def7cde --tag-specifications ResourceType=instance,Tags=[{Key=Name,Value=First-Jenkins}]'
        }
      }
    }
    stage('Deploy') {
      steps {
        // Add deployment steps here
        echo 'Deploying...'
      }
    }
  }
}
